# -*- coding: utf-8 -*-
# Autorska mapa 159 unikalnych plikow korpusu Eternal -> 4 sekcje.
# S=Specyfikacja  B=Biznesplan  R=Roadmapa  P=Pitch
# status: FINAL | ZASTAPIONY:<idx> | DUPLIKAT:<idx> | UNIKAT | SUROWIEC
M = {
# --- ETL 001-030 (analizy tematyczne, files_4) ---
1:("R","UNIKAT","Plan 90 dni - rozpisanie pierwszego kwartalu wykonania; wchodzi do Etapu 1 roadmapy."),
2:("S","UNIKAT","Pokrycie API: ktore funkcje da sie zrealizowac na gotowych API vs wlasny kod."),
3:("S,B","UNIKAT","Plan wobec IKP: pozycjonowanie wzgledem panstwowego IKP; do rozdz. rynek i integracje."),
4:("S","UNIKAT","Katalog urzadzen wearables + protokoly; zrodlo tabeli integracji sprzetowych."),
5:("S","UNIKAT","Ocena modulow - ktore moduly sa gotowe/ryzykowne; do oceny dojrzalosci funkcji."),
6:("S","UNIKAT","Capsule FINAL - docelowy ksztalt warstwy wewnatrzustrojowej."),
7:("S","UNIKAT","e-Profil Pacjenta jako zrodlo agregacji - REST/OpenAPI, bariera prawna nie techniczna."),
8:("S","UNIKAT","Klasy komponentow K01-K28 - taksonomia komponentowa specyfikacji."),
9:("B","UNIKAT","Marketplace/Hub/Forge - modele przychodu z warstwy posredniczacej."),
10:("R","UNIKAT","Sekwencja wykonawcza - kolejnosc realizacji wynikajaca z zaleznosci."),
11:("S","UNIKAT","Moduly kontrolne K1-K14 - warstwa nadzoru nad funkcjami."),
12:("S","UNIKAT","Model software - podzial na warstwy aplikacyjne."),
13:("S","UNIKAT","Taksonomia Master - slownik pojec spinajacy rejestr funkcji."),
14:("B","UNIKAT","Werdykt planu - ocena wykonalnosci calosci; do rozdz. ryzyka."),
15:("B","UNIKAT","Podstawy monetyzacji - fundament cennika i modeli przychodu."),
16:("B","UNIKAT","Skala/czas/kontrola - trojkat ograniczen projektu."),
17:("S,B","UNIKAT","Podmiot i zgody - RODO art.9, podstawy przetwarzania, rola podmiotu leczniczego."),
18:("S","UNIKAT","Braki specyfikacji - jawna lista luk; zrodlo znacznikow [BRAK] w dokumencie."),
19:("B","UNIKAT","Statut Fundacji - cel statutowy, golden share, kontrola IP."),
20:("R,B","UNIKAT","Podprojekty macierzy - dekompozycja 40 projektow na podprojekty."),
21:("S","UNIKAT","Model strukturalny - relacja Cel-Projekt-Produkt-Funkcja."),
22:("B","UNIKAT","Rentownosc a wlasnosc - kiedy wlasne IP oplaca sie bardziej niz licencja."),
23:("S","UNIKAT","Architektura w horyzoncie 50 lat - wymagania trwalosci danych."),
24:("S,B","UNIKAT","BCI: OEM vs licencja - analiza make-or-buy dla interfejsow neuronowych."),
25:("S,B","UNIKAT","Certyfikacja a kontrola - koszt certyfikacji vs utrata kontroli nad IP."),
26:("B","UNIKAT","Polska e-zdrowie 2030 - otoczenie regulacyjne i KPO; do rozdz. rynek."),
27:("B","UNIKAT","Mapowanie na panstwo - punkty styku z NFZ/CeZ/P1."),
28:("S,B","UNIKAT","Agregacja a kontrola - czy agregator moze dzialac bez certyfikacji MDR."),
29:("B,P","UNIKAT","Konkurencja w ekosystemie - mapa graczy; zrodlo slajdu konkurencji."),
30:("S","UNIKAT","Capsule a kontrola - warstwa implantow i granice sterowania (tylko odczyt)."),
# --- eternal_1 / files_6 (dokumenty robocze) ---
31:("B","UNIKAT","Profil agentow i wiarygodnosc - metodyka oceny zrodel."),
32:("S","FINAL","Rejestr FINALNY 309 funkcji w 42 modulach - kanoniczny rejestr calego ekosystemu."),
33:("B","ZASTAPIONY:36","IKP i P1 do 2030 - wczesniejsza wersja horyzontu."),
34:("S,B","UNIKAT","Dane zweryfikowane - liczby potwierdzone zrodlowo; nadpisuja szacunki."),
35:("S","UNIKAT","Splaszczenie punktu 5 - uproszczenie hierarchii projektow."),
36:("B","FINAL","IKP i P1 do 2031 - aktualniejszy horyzont integracji panstwowej."),
37:("B","UNIKAT","Marketing i wspoldecydowanie - model relacji z uzytkownikiem."),
38:("R","UNIKAT","Punkt zerowy - stan wyjsciowy przed Etapem 1."),
39:("S","ZASTAPIONY:32","Aplikacja w 23 modulach - wczesniejszy podzial modulowy."),
40:("B","UNIKAT","Model doboru projektow - kryteria wyboru z 40 projektow."),
41:("S","UNIKAT","Przebieg MVP: odczyt wyniku - kluczowa sciezka uzytkownika end-to-end."),
42:("S","UNIKAT","Sprzet noszony i diagnostyka - warstwa hardware wearables."),
43:("S","UNIKAT","Struktura warstwowa - warstwy przeznaczenia A/B/C."),
44:("B,S","UNIKAT","Capsule realizacja tania - wariant niskokosztowy warstwy implantow."),
45:("B,P","UNIKAT","Pole gry: IKP i konkurencja - pozycjonowanie; do slajdu 'dlaczego my'."),
46:("B","UNIKAT","Skad roznica kosztow - wyjasnienie rozbieznosci wycen miedzy wersjami."),
47:("B","UNIKAT","Status kliniki i freemium - czy potrzebny podmiot leczniczy przy modelu freemium."),
48:("S","UNIKAT","Dokument ujednolicony - wczesna proba scalenia; wzorzec struktury."),
49:("R,B","UNIKAT","Piec projektow i moonshoty - podzial P1-P5 + moonshoty."),
50:("S","UNIKAT","Struktura Cel-Projekt-Produkt-Funkcja - kanoniczna hierarchia."),
51:("S","ZASTAPIONY:32","Rejestr scalony 299 funkcji - poprzednik rejestru 309."),
52:("B","UNIKAT","Model monetyzacji - warstwy przychodu."),
53:("R","UNIKAT","Punkt 2: moonshoty - definicje moonshotow."),
54:("B","ZASTAPIONY:77","Piec punktow v2 - wczesniejsza wersja pieciu rozstrzygniec."),
55:("R,P","UNIKAT","Wizja 2036-2046 - horyzont dlugoterminowy; do slajdu wizji."),
56:("S","UNIKAT","Funkcje: ewolucja i luki - jak rejestr funkcji rosl i czego brakuje."),
57:("B,R","FINAL","Punkt 5 pelny: 40 projektow - pelna lista projektow macierzy."),
58:("B","UNIKAT","Modele monetyzacji i piwoty - warianty przychodowe i sciezki wyjscia."),
59:("R,B","UNIKAT","Projekty P1-P5: definicja - priorytetyzacja portfela."),
60:("B","UNIKAT","Analiza macierzy i modele - metodyka macierzy 40 projektow."),
61:("S","UNIKAT","Audyt 185 funkcji - weryfikacja rejestru funkcji aplikacji."),
62:("B","UNIKAT","Warstwy, produkty, monetyzacja - mapowanie warstw na przychod."),
63:("B","UNIKAT","Punkt 3: otwarty system - strategia otwartosci/standardu Eternal."),
64:("S","UNIKAT","Punkt 1: dekompozycja - rozbicie ekosystemu na czesci skladowe."),
65:("B,R","ZASTAPIONY:128","Macierz skondensowana v3 - poprzednik Macierzy 40 Projektow v2 z PDF."),
66:("B","UNIKAT","Trzy warianty wykonania - scenariusze realizacji (tani/sredni/pelny)."),
67:("S","UNIKAT","Architektura komponentow - rozklad na komponenty techniczne."),
68:("S","UNIKAT","Struktura merytoryczna - uklad tresci dokumentacji."),
69:("S,R","UNIKAT","Jak to zbudowac - praktyczna sciezka techniczna."),
70:("B","UNIKAT","Weryfikacja hipotez - testowanie zalozen biznesowych."),
71:("R","UNIKAT","Projekty: forma, lata, kolejnosc - harmonogram portfela."),
72:("B","UNIKAT","Punkt 4: trzon i kontrola - co musi zostac wlasne."),
73:("R","UNIKAT","Dekompozycja i sekwencja - kolejnosc wykonania."),
74:("P,B","UNIKAT","Co nas wyroznia - bezposrednie zrodlo slajdu przewagi konkurencyjnej."),
75:("S,P","UNIKAT","Karty produktowe 1-20 - opisy produktow; do slajdow produktowych."),
76:("B","UNIKAT","Eternal jako projekt publiczny - wariant partnerstwa publicznego."),
77:("B","FINAL","Piec rozstrzygniec - kluczowe decyzje strategiczne (wersja ostateczna)."),
78:("S","UNIKAT","30 modulow: pelna analiza - rozszerzenie analizy modulowej."),
79:("B","FINAL","Piec odpowiedzi poprawione - skorygowana wersja piatki odpowiedzi."),
80:("S","UNIKAT","Specyfikacja i architektura - wczesny rdzen specyfikacji technicznej."),
81:("B","ZASTAPIONY:79","Piec odpowiedzi - wersja przed poprawkami."),
82:("S,B","UNIKAT","Dokumentacja kompletna (110k) - najobszerniejszy dokument scalony z eternal_1."),
# --- ETL 030-032 ---
83:("S","ZASTAPIONY:32","23 moduly / 160 funkcji - wczesniejszy stan rejestru."),
84:("B","UNIKAT","Struktura przychodow - rozbicie strumieni przychodu."),
85:("S","UNIKAT","Specyfikacja scalona - proba konsolidacji specyfikacji."),
# --- files_5: zestawienia 115 funkcji ---
86:("B,S","UNIKAT","Macierz dostawcow - kto dostarcza ktory komponent i za ile."),
87:("S","SUROWIEC","Analiza ChatGPT - material zrodlowy, nizsza wiarygodnosc; tylko weryfikowalne fragmenty."),
88:("S,B","UNIKAT","Model agregacyjny bez certyfikacji - kluczowa teza o dzialaniu ponizej progu MDR."),
89:("S","UNIKAT","Komponenty + linki - konkretne biblioteki/uslugi z odnosnikami i licencjami."),
90:("S","ZASTAPIONY:126","Master 3.1 (skrot) - zastapiony przez Master 5.4."),
91:("S","UNIKAT","Produkty i moduly posrednie - warstwa posrednia miedzy produktem a funkcja."),
92:("S","UNIKAT","Kiedy MDR - 115 funkcji z progiem wyrobu medycznego; kluczowa tabela compliance."),
93:("S","UNIKAT","Audyt odpowiedzi - weryfikacja wczesniejszych ustalen."),
94:("B","UNIKAT","Analiza krytyczna: koszty certyfikacji - realne widelki kosztow certyfikacji."),
95:("S","ZASTAPIONY:125","App specyfikacja funkcjonalna - wczesna wersja specyfikacji aplikacji."),
96:("S","UNIKAT","Punkty wspolne (tresc) - czesci wspolne miedzy funkcjami; podstawa reguly 33%."),
97:("S,B","UNIKAT","Rozwiazania MDR/IKP - jak omijac lub spelniac wymogi legalnie."),
98:("S,B","UNIKAT","Odpowiedzi: certyfikacja, kontrola, struktura - rozstrzygniecia regulacyjne."),
99:("S","UNIKAT","3 zestawienia po audycie - skorygowane zestawienia funkcji."),
100:("S,B","UNIKAT","Odpowiedzi na pytania - rozstrzygniecia mieszane techniczno-biznesowe."),
101:("S","UNIKAT","Analiza relacyjna 115 funkcji - zaleznosci miedzy funkcjami."),
102:("B","UNIKAT","Alternatywy: koszty i kontrola - warianty make/buy z wycena."),
103:("S,B","UNIKAT","Funkcje: certyfikacja i licencje - licencje OSS per funkcja (pulapki AGPL)."),
104:("S","UNIKAT","Analiza zbiorcza - zbiorcze zestawienie ustalen."),
105:("S","FINAL","115 funkcji: grupy, agregacja, system - kanoniczne zestawienie 115 funkcji."),
106:("S,B","UNIKAT","Odpowiedzi pytanie po pytaniu - najszersze rozstrzygniecia w files_5."),
107:("S","UNIKAT","System punktow wspolnych (86k) - pelny system komponentow wspoldzielonych."),
# --- specyfikacje glowne ---
108:("S","ZASTAPIONY:125","App Specyfikacja 3.1 (602k) - poprzednik App 5.4."),
109:("S","ZASTAPIONY:126","Master 3.1 KOMPLETNA (922k) - poprzednik Master 5.4."),
# --- pitch ---
110:("P","FINAL","Pitch App (pptx) - struktura narracji dla samej aplikacji."),
111:("P","FINAL","Pitch Ekosystem (pptx) - struktura narracji dla calego ekosystemu."),
# --- ETL 031-037 ---
112:("S,B","UNIKAT","Rejestr pytan ujednolicony - lista otwartych kwestii projektu."),
113:("S","UNIKAT","Weryfikacja odpowiedzi zewnetrznych - kontrola jakosci ustalen."),
114:("S","UNIKAT","Audyt pokrycia zrodel - ktore tezy maja pokrycie w zrodlach."),
115:("S","UNIKAT","Model odpowiedzi - metodyka udzielania rozstrzygniec."),
116:("R","ZASTAPIONY:158","Roadmapa wykonawcza 2.0 - wczesna roadmapa, zastapiona przez checklisty v5."),
117:("S","UNIKAT","Eternal API Gateway - specyfikacja bramy API ekosystemu."),
118:("S,B","UNIKAT","Wykonalnosc naukowa i kontrola technologii - TRL i realnosc moonshotow."),
119:("S","UNIKAT","Model orkiestratora - warstwa orkiestracji (istotna dla kosztu MVP)."),
120:("B","UNIKAT","Hub i Forge - model dwoch platform posredniczacych."),
121:("B","UNIKAT","Audyt oceny wykonalnosci - niezalezna ocena realnosci planu."),
122:("B","ZASTAPIONY:123","Biznesplan 4.0 - poprzednik Planu Korporacyjnego 5.1."),
123:("B","FINAL","Plan Korporacyjny 5.1 - najnowszy zwiezly dokument biznesowy; szkielet biznesplanu."),
124:("R,B","UNIKAT","Dwie powierzchnie, etapy, waga - model etapowania z wagami."),
125:("S","FINAL","App Specyfikacja 5.4 FINAL (752k) - KANON specyfikacji aplikacji."),
126:("S,B","FINAL","Specyfikacja Master 5.4 FINAL (1,07M) - KANON calego ekosystemu; nadpisuje 3.0/3.1."),
# --- pozostale ---
127:("S","UNIKAT","Normy aplikacji medycznej - lista norm do przestrzegania."),
128:("B,R","FINAL","Macierz 40 Projektow v2 - kanoniczna macierz portfela projektow."),
129:("S","ZASTAPIONY:126","Master 3.0 KOMPLETNA (745k) - poprzednik; zachowany dla historii zmian."),
130:("S,B","SUROWIEC","Pytania bez odpowiedzi - otwarte kwestie do rozstrzygniecia."),
131:("S,B","SUROWIEC","Konwersacja ChatGPT (190k) - material zrodlowy; tylko potwierdzone ustalenia."),
132:("S,B","SUROWIEC","Konwersacja ChatGPT drugie konto (268k) - jw."),
133:("B","UNIKAT","Master WBS Holdingu - struktura podzialu prac holdingu."),
134:("S","ZASTAPIONY:32","Moduly (pdf) - wczesniejsze zestawienie modulow."),
135:("S","UNIKAT","Agregacja danych z wearables - szczegoly techniczne agregacji."),
136:("R","FINAL","Etapy 7-11: fikcja SF/lore - kanon warstwy fikcyjnej roadmapy."),
137:("B","UNIKAT","DeepSeek: analiza (26k) - zewnetrzna analiza, czesc unikalna."),
138:("P","FINAL","OFICJALNY PITCH DECK (pdf) - WZORZEC WIZUALNY I NARRACYJNY dla sekcji Pitch."),
139:("S,B","SUROWIEC","Same pytania (ujednolicone) - lista pytan bez odpowiedzi."),
140:("B,P","FINAL","Podsumowanie wykonawcze (53k) - gotowe streszczenie zarzadcze; rdzen pitcha."),
141:("B","UNIKAT","DeepSeek 5d6d38 (64k) - zewnetrzna analiza biznesowa."),
142:("B","UNIKAT","DeepSeek 5f7054 (80k) - zewnetrzna analiza biznesowa."),
143:("B","UNIKAT","DeepSeek 5c7a80 (116k) - najobszerniejsza analiza DeepSeek."),
144:("B,R","FINAL","Etap 2 'Budowa firmy' kompletna (188k) - pelne rozpisanie etapu 2."),
145:("B","FINAL","Biznesplan rozszerzony (404k) - NAJOBSZERNIEJSZY biznesplan; rdzen sekcji B."),
146:("S,B","SUROWIEC","Pytania + odpowiedzi (592k) - najwiekszy zbior rozstrzygniec Q&A."),
147:("R","ZASTAPIONY:158","Checklist v2 realny - najstarsza checklista."),
148:("S","DUPLIKAT:129","Master 3.0 .docx.pdf - roznica 6 slow wobec #129; pomijany."),
149:("R","ZASTAPIONY:151","Moonshoty roadmapa od nowa - wariant bazowy."),
150:("R","ZASTAPIONY:151","Moonshoty + wskazane epiki strategiczne - wariant 2 (95,5% zgodny z 149)."),
151:("R","FINAL","Moonshoty + strategiczne EPIC/TASK/SUBTASK SF - najpelniejszy wariant moonshotow."),
152:("R","UNIKAT","Checklist v5 etapy 7-11 - JEDYNE zrodlo analizy 40/40 projektow (powiazania, alternatywa, moat, koszt)."),
153:("R","ZASTAPIONY:158","Checklist v3 pelny - zrodlo pol Kto/Kiedy/Czas trwania."),
154:("R","FINAL","Checklist v4 alternatywy - KANON katalogu Tor A/Tor B i scenariuszy A/B."),
155:("R","ZASTAPIONY:158","Checklist v5 SKROCONA etapy 1-6 - realny plan w skrocie."),
156:("R","ZASTAPIONY:158","Checklist bazowy - najglebszy rozklad na subtaski (1054/4312/13954)."),
157:("R","ZASTAPIONY:158","Checklist v5 pelna analiza - poprzednik wersji PWNS."),
158:("R,B","FINAL","Checklist v5 PWNS - KANON roadmapy: v5 + warstwa operacyjna 188 pkt, zespol, stack locked, koszty PL 2026."),
159:("R","FINAL","Checklist enriched - KANON warstwy 'jak wyglada/kto buduje/budzet USD/stack' per etap."),
}
